mscApplications/evaluator/urls.py
from django.urls import  path
from .views import *

app_name = 'evaluator'

urlpatterns = [
    path('home', EvaluatorHomeView.as_view(), name='evaluator_home'),
    path('profile', EvaluatorProfileDetailView.as_view(), name='evaluator_profile'),
    path('profile/edit', EvaluatorProfileUpdateView.as_view(), name='evaluator_profile_edit'),
    path('calls', EvaluatorCallListView.as_view(),name='evaluator_calls'),
    path('create', EvaluatorCreateView.as_view(),name='evaluator_create'),
    path('<int:pk>/delete', EvaluatorDeleteView.as_view(),name='evaluator_delete'),
    path('<int:pk>/update', EvaluatorUpdateView.as_view(),name='evaluator_update'),

]

mscApplications/institution/urls.py
from django.urls import  path
from .views import *

app_name = 'org'

urlpatterns = [
    path('institutions/<int:pk>/detail/', InstitutionDetailView.as_view(), name='institution_detail'),
    path('departments/<int:pk>/detail/', DepartmentDetailView.as_view(), name='department_detail'),
]

mscApplications/msc/urls.py
from django.urls import  path
from .views import *

app_name = 'msc'

urlpatterns = [
    path('calls', CallListView.as_view(), name='call_list'),
    path('calls/create', CallCreateView.as_view(), name='call_create'),
    path('calls/<int:pk>/detail', CallDetailView.as_view(), name='call_detail'),
    path('calls/<int:pk>/delete', CallDeleteView.as_view(), name='call_delete'),
    path('calls/<int:pk>/update', CallUpdateView.as_view(), name='call_update'),
    path('calls/<int:pk>/applications', ApplicationListView.as_view(), name='call_application_list'),
    path('calls/<int:pk>/new-application', ApplicationCreateView.as_view(), name='call_new_application'),
    path('calls/<int:call_pk>/applications/<int:pk>/admit', ApplicationAdmitView.as_view(), name='call_application_admit'),
    path('programmes', MscProgrammeListView.as_view(), name='msc_programme_list'),
    path('programmes/create', MscProgrammeCreateView.as_view(), name='msc_programme_create'),
    path('programmes/<int:pk>', MscProgrammeDetailView.as_view(), name='msc_programme_detail'),
    path('programmes/<int:pk>/edit', MscProgrammeUpdateView.as_view(), name='msc_programme_update'),
    path('programmes/<int:pk>/delete', MscProgrammeDeleteView.as_view(), name='msc_programme_delete'),
]

mscApplications/mscApplications/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from .views import HomeView


urlpatterns = [
    path("accounts/", include("allauth.urls")),
    path("users/", include("user_account.urls", namespace="user_account")),
    path(
        "applicant/",
        include(
            "applicant.urls",
            namespace="applicant",
        ),
    ),
    path(
        "evaluator/",
        include("evaluator.urls",
        namespace="evaluator",
        ),
    ),
    path(
        "secretary/",
        include("secretary.urls",
        namespace="secretary",
        ),
    ),
    path(
        "msc/",
        include("msc.urls",
        namespace="msc",
        ),

    ),
    path(
        "org/",
        include("institution.urls",
        namespace="org",
        ),

    ),
    path("", HomeView.as_view(), name='home'),
    path("admin/", admin.site.urls),
    path("i18n/", include("django_translation_flags.urls")),
]
if settings.DEBUG==True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mscApplications/user_account/urls.py
from django.conf.urls import url
from django.urls import path, include
from .views import *
from django.contrib.auth import views as auth_views

app_name = "user_account"


urlpatterns = [
    path("check", CheckUser.as_view(), name="check-user"),
    path("change-password", ChangePasswordView.as_view(), name="user_change_password"),
]

mscApplications/evaluator/models.py
from django.db import models
from django.core.exceptions import ObjectDoesNotExist
from django.utils.translation import gettext as _

from utils.validators import telephone_validator
from institution.models import Department
from django.conf import settings

class Evaluator(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL,related_name='evaluator', on_delete=models.CASCADE,primary_key=True)
    telephone = models.CharField(_('Telephone'),max_length = 10,validators=[telephone_validator])
    department = models.ForeignKey(Department,on_delete=models.SET_NULL,null=True)

    def __str__(self):
        try:
            return self.user.first_name+" "+self.user.last_name
        except ObjectDoesNotExist:
            return self.telephone

    class Meta:
        verbose_name = _("Evaluator")
        verbose_name_plural = _("Evaluators")

mscApplications/msc/models.py
from django.db import models
from institution.models import Department
from django.utils.translation import gettext as _
from evaluator.models import Evaluator
from django.db import models
from applicant.models import Applicant,Reference
from .utils import application_upload
from django.core.validators import FileExtensionValidator

class MscProgramme(models.Model):
    title = models.CharField(_('Title'),max_length = 200)
    address = models.CharField(_('Address'),max_length=50)
    description=models.TextField(_('description'),null=True,blank=True)
    department=models.ForeignKey(Department,on_delete=models.CASCADE, verbose_name=_("Department"))

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _("MSC Programme")
        verbose_name_plural = _("MSC Programmes")

class MscFlow(models.Model):
    title = models.CharField(_('Title'),max_length = 200)
    msc_programme=models.ForeignKey(MscProgramme,on_delete=models.CASCADE,verbose_name=_("Msc Programme"))

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _("MSC Flow")
        verbose_name_plural = _("MSC Flows")


class Call(models.Model):
    title = models.CharField(_('Title'),max_length = 200)
    start_date=models.DateField(_('Start date'))
    end_date=models.DateField(_('End Date'))
    msc_programme=models.ForeignKey(MscProgramme,on_delete=models.CASCADE, verbose_name=_("Msc Programme"))
    evaluators = models.ManyToManyField(
        Evaluator, blank=False)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _("Call")
        verbose_name_plural = _("Calls")

class Application (models.Model):
    applicant=models.ForeignKey(Applicant,on_delete=models.CASCADE)
    call=models.ForeignKey(Call,on_delete=models.CASCADE)
    submission_date=models.DateField(_('Submission Date'),auto_now_add=True)
    comments=models.TextField(_('Comments'),null=True,blank=True)
    admitted=models.BooleanField(_('Admitted'),default=None,null=True,blank=True)
    reference=models.ForeignKey(Reference,on_delete=models.SET_NULL,null=True,blank=True)
    media_file = models.FileField(_('Media File'),upload_to=application_upload,validators=[FileExtensionValidator(allowed_extensions=['pdf'])])
    preferences = models.ManyToManyField(MscFlow,through='Preference',blank=True,related_name="waiting_applications")
    admitted_flow=models.ForeignKey(MscFlow,on_delete=models.CASCADE,blank=True,null=True,related_name="admitted_application")

    def __str__(self):
        return self.applicant.user.email+" application"

    class Meta:
        verbose_name = _("Application")
        verbose_name_plural = _("Applications")
        constraints = [
        models.UniqueConstraint(fields=['applicant', 'call'], name='unique call for applicant')
    ]
class Preference(models.Model):
    application = models.ForeignKey(Application, on_delete=models.CASCADE)
    flow = models.ForeignKey(MscFlow,on_delete=models.CASCADE)
    priority = models.PositiveIntegerField(_('Priority'),)

    class Meta:
        ordering = ["priority"]
        verbose_name = _("Priority")
        verbose_name_plural = _("Priorities")

    def __str__(self):
        return  self.flow.title

mscApplications/evaluator/forms.py
from django import forms
from user_account.models import User
from .models import Evaluator
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Row, Column
from django.utils.translation import gettext_lazy as _

from django.contrib.auth.forms import UserCreationForm
from utils.validators import telephone_validator

class EvaluatorForm(forms.ModelForm):
    first_name = forms.CharField(max_length=30, label=_('First Name'))
    last_name = forms.CharField(max_length=30, label=_('Last Name'))
    class Meta:
        model = Evaluator
        fields = ("first_name", "last_name", "telephone")

    def __init__(self, *args, **kwargs):
        super(EvaluatorForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.layout = Layout(
            Row(
                Column("first_name", css_class="form-group col-md-6 mb-0"),
                Column("last_name", css_class="form-group col-md-6 mb-0"),
                css_class="form-row",
            ),
            "telephone",
        )

class EvaluatorCreateForm(UserCreationForm):
    telephone = forms.CharField(max_length=10, label=_('Telephone'),validators=[telephone_validator])

    class Meta:
        model = User
        fields = ('email','first_name','last_name','password1','password2','telephone')

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop("user")
        super(EvaluatorCreateForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()  
        self.helper.form_tag = False
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-lg-4'
        self.helper.field_class = 'col-lg-8'
        
    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        user.is_evaluator=True
        if commit:
            user.save()
            Evaluator.objects.create(user=user,telephone=self.cleaned_data["telephone"],department=self.user.secretary.department)
        return user

class EvaluatorUpdateForm(forms.ModelForm):
    first_name = forms.CharField(max_length=30, label=_('First Name'))
    last_name = forms.CharField(max_length=30, label=_('Last Name'))

    class Meta:
        model = Evaluator
        fields = ('first_name','last_name','telephone')

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop("user")
        super(EvaluatorUpdateForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()  
        self.helper.form_tag = False
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-lg-4'
        self.helper.field_class = 'col-lg-8'

    def save(self, commit=True):
        evaluator = super().save(commit=False)
        if commit:
            evaluator.department=self.user.secretary.department
            evaluator.save()
            evaluator.user.first_name=self.cleaned_data['first_name']
            evaluator.user.last_name=self.cleaned_data['last_name']
            evaluator.user.save()
        return evaluator

mscApplications/evaluator/views.py
from msc.models import Call
from .forms import *
from .models import Evaluator
from django.views.generic import UpdateView,DetailView,TemplateView,ListView,CreateView,DeleteView
from django.urls import reverse_lazy,reverse
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.utils.translation import ugettext_lazy as _
from utils.mixins import *
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin


class EvaluatorHomeView(LoginRequiredMixin,EvaluatorRequiredMixin,TemplateView):
    template_name='evaluator_home.html'


class EvaluatorProfileDetailView(LoginRequiredMixin,EvaluatorRequiredMixin,DetailView):
    model=Evaluator
    context_object_name = 'evaluator'
    template_name = 'evaluator_profile.html'

    def get_object(self):
        return self.request.user.evaluator


class EvaluatorProfileUpdateView(LoginRequiredMixin,EvaluatorRequiredMixin,UpdateView):
    model = Evaluator
    form_class=EvaluatorForm
    template_name = 'evaluator_profile_edit.html'
    success_url = reverse_lazy('evaluator:evaluator_profile')

    def get_form(self, *args, **kwargs):
        form = super().get_form(*args, **kwargs)
        form.fields['first_name'].initial = self.request.user.first_name
        form.fields['last_name'].initial = self.request.user.last_name
        return form

    def form_valid(self,form):
        user=form.instance.user
        user.first_name=form.cleaned_data['first_name']
        user.last_name=form.cleaned_data['last_name']
        user.save()
        messages.success(self.request, (_('Your profile has been updated.')))
        return super().form_valid(form)

    def get_object(self,queryset=None):
        return self.request.user.evaluator


class EvaluatorCallListView(LoginRequiredMixin,EvaluatorRequiredMixin,ListView):
    model=Call
    context_object_name='calls'
    template_name='evaluator_calls.html'

    def get_queryset(self):
        queryset = Call.objects.filter(evaluators__pk=self.request.user.id)
        return queryset

class EvaluatorCreateView(LoginRequiredMixin,SuccessMessageMixin,SecretaryRequiredMixin,CreateView):
    template_name='evaluator_create.html'
    form_class=EvaluatorCreateForm
    success_message = _('Evaluator created !')
    success_url = reverse_lazy('secretary:secretary_evaluators')

    def get_form_kwargs(self):
        kwargs = super(EvaluatorCreateView, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

class EvaluatorUpdateView(LoginRequiredMixin,SuccessMessageMixin,SecretaryRequiredMixin,UserPassesTestMixin,UpdateView):
    template_name='evaluator_update.html'
    model=Evaluator
    form_class=EvaluatorUpdateForm
    success_message = _('Evaluator updated !')
    success_url = reverse_lazy('secretary:secretary_evaluators')

    def test_func(self):
        user = self.request.user
        if user.has_secretary():
            if self.get_object().department==user.secretary.department:
                return True
        return False

    def get_form(self, *args, **kwargs):
        form = super().get_form(*args, **kwargs)
        form.fields['first_name'].initial = self.get_object().user.first_name
        form.fields['last_name'].initial = self.get_object().user.last_name
        return form

    def get_form_kwargs(self):
        kwargs = super(EvaluatorUpdateView, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

class EvaluatorDeleteView(LoginRequiredMixin,SecretaryRequiredMixin,UserPassesTestMixin,DeleteView):
    model=Evaluator

    def test_func(self):
        user = self.request.user
        if user.has_secretary():
            if self.get_object().department==user.secretary.department:
                return True
        return False

    def get_success_url(self):
        messages.success(self.request, (_('Evaluator deleted.')))
        return reverse('secretary:secretary_evaluators')

mscApplications/evaluator/templates/application_admit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% load i18n %}
{%block title %} {% trans "Admit application" %}{% endblock title %}
{% block content%}
{% get_current_language as LANGUAGE_CODE %}

<form
  enctype="multipart/form-data"
  class="form-special"
  action="."
  method="post"
>
  {% csrf_token %}
  <div class="card">
    <div class="card-header msc-color text-white">{% trans "Admit application" %}</div>
    <div class="card-body">
      <div class="container">
      <div class="row">
        <div class="col-md-6">
          <label>{% trans "Submission Date" %}</label>
        </div>
        <div class="col-md-6">
          <p>{{application.submission_date}}</p>
        </div>
      </div>
      <hr />
      <div class="row">
        <div class="col-md-6">
          <label>{% trans "Programme" %}</label>
        </div>
        <div class="col-md-6">
          <p> {% if LANGUAGE_CODE == 'el-gr' %}
            {{application.call.msc_programme.title_el_GR}}
        {% else %}
            {{application.call.msc_programme}}
        {% endif %}</p>
        </div>
      </div>
      <hr />
      <div class="row">
        <div class="col-md-6">
          <label>{% trans "Reference" %}</label>
        </div>
        {% if application.reference %}
        <div class="col-md-6"><a href="{{application.reference.media_file.url}}">{{application.reference}}</a></div>
        {% else %}
        <div class="col-md-6">{% trans "None" %}</div>
        {% endif %}
      </div>
      <hr />
      <div class="row">
        <div class="col-md-6">
          <label>{% trans "Media File" %}</label>
        </div>
        <div class="col-md-6"><a href="{{application.media_file.url}}">{{application.media_file}}</a></div>
      </div>
      <hr />
      {% if application.preference_set.all %}
      <h5 >{% trans "Flows by prefered Order" %}</h5>
      <table style="width:40%">
        <thead>
          <tr>
            <th>{% trans "Priority" %}</th>
            <th >{% trans "Flow" %}</th>
          </tr>
        </thead>
        <tbody>
          {% for pref in application.preference_set.all %}
              <tr>
                <td>{{pref.priority}}</td>
                <td> {% if LANGUAGE_CODE == 'el-gr' %}
                  {{pref.flow.title_el_GR}}
              {% else %}
                  {{pref.flow}}
              {% endif %}</td>
              </tr>
           {% endfor %}
        </tbody>
      </table>
      <br>
      <div class="row">
        <div class="col-md-6">
          <label>{% trans "Admitted Flow" %}</label>
        </div>
        <div class="col-md-6">{{ form.admitted_flow |as_crispy_field }}</div>
      </div>
      <hr />
      {% endif %}
      <div class="row">
        <div class="col-md-6">
          <label>{% trans "Admitted" %}</label>
        </div>
        <div class="col-md-6">{{ form.admitted |as_crispy_field }}</div>
      </div>
      <hr />
      <button type="submit" class="btn msc-color text-white">{% trans "Submit" %}</button>
    </div>
    </div>
  </div>
</form>
{% endblock content %}

mscApplications/evaluator/templates/evaluator_calls.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{%block title %} {% translate "My Calls" %} {% endblock title %}
{% block content%}
{% if calls %}
    {% for call in calls %}
        <div class="card ">
            <div class="card-header msc-color text-white">
                <h5 style="display: inline">
                        {{ call.title }}
                </h5>
                <span class="float-end"><a href="{% url 'msc:call_detail' call.pk %}" class="btn btn-outline-light btn-md rounded-pill">{% translate "View Call" %}</a></span>
            </div>
            <div class="card-body ">
                <p><strong>{% translate "Start Date" %}:</strong> {{ call.start_date }}</p>
                <p><strong>{% translate "End Date" %}:</strong> {{ call.end_date }}</p>
                <p><strong>{% translate "Msc Programme" %}:</strong>{{ call.msc_programme }}</p>
            </div>
            <div class="card-footer msc-color " >
                <a href="{% url 'msc:call_application_list' call.pk %}" class="btn btn-outline-light btn-md rounded-pill float-rigth">{% translate "View Applications" %}</a>
            </div>
        </div>
    {% endfor %}
{% else %}
    <div class="row">
        <div class="col col-12">
            <div class="alert alert-danger">{% translate "No calls found " %}</div>
        </div>
    </div>
{% endif %}
{% endblock content %}

mscApplications/evaluator/templates/evaluator_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load i18n %}
{% block title %}{% translate "Create Evaluator" %}{% endblock title %}

{% block content %}
  <div class="card">
    <form method="post">
      <div class="card-header msc-color text-white">
        <h5 style="display: inline">
          {% translate "Create Evaluator" %}
        </h5>
      </div>
      <div class="card-body">
        <div class="container">
          {% csrf_token %}
          {% crispy form %}
        </div>
      </div>
      <div class="card-footer msc-color">
        <button type="submit" class="btn btn-outline-light rounded-pill">{% translate "Submit" %}</button>
      </div>
    </form>
  </div>
{% endblock %}

mscApplications/evaluator/templates/evaluator_home.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{%block title %} {% translate "Home" %} {% endblock title %}
{% block content%}

<div class="card ">
    <div class="card-header msc-color text-white">
        <h5 style="display: inline">{% translate "Welcome" %}</h5>
    </div>
    <div class="card-body ">
        <h4>{% translate "Instructions" %}</h4>
        <br>
        <div class="container">
        <p>1. {% translate "Click" %} <a href="{% url 'evaluator:evaluator_calls' %}">{% translate "My Calls" %}</a> {% translate "to see your assigned call ." %}</p>
        <p>1. {% translate "Click" %} {% translate "View Applications" %} {% translate "to see the applications you have to check about your assigned call ." %}</p>
        <p>2. {% translate "Click View Application to check if the application is accepted ." %}</p>
        <p>3. {% translate "Select Admitted and Admitted Flow to accept the application." %}</p>
    </div>
    </div>
</div>
{% endblock content %}

mscApplications/evaluator/templates/evaluator_profile.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block title %}{% translate "Profile" %} {% endblock title %}
{% block content %}

    <div class="row">
        <div class="col-md-3 text-center">
            <div class="profile-image">
                <i class="bi bi-person-circle big-icon"></i>
            </div>
            <h3>{% translate "Actions" %} :</h3>
            <a class="btn btn-outline-success rounded-pill" href="{% url 'evaluator:evaluator_profile_edit' %}">{% translate "Edit Profile" %}</a>
            <div style="padding-top:10px;">
                <a class="btn btn-outline-success rounded-pill" href="{% url 'user_account:user_change_password' %}">{% translate "Change Password" %}</a>
            </div>
        </div>
        <div class="col-md-9">
            <br>
            <div class="profile-head">

                <h6>{{evaluator.user.email}}</h6>

            </div>
            <br><br>
            <div class="row">
                <div class="col-sm-4">
                    <h6 class="mb-0">{% translate "First Name" %}</h6>
                </div>
                <div class="col-sm-8 text-secondary">{{evaluator.user.first_name}}  </div>
            </div>
            <hr>
            <div class="row">
                <div class="col-sm-4">
                    <h6 class="mb-0">{% translate "Last Name" %}</h6>
                </div>
                <div class="col-sm-8 text-secondary">{{evaluator.user.last_name}}  </div>
            </div>
            <hr>
            <div class="row">
                <div class="col-sm-4">
                    <h6 class="mb-0">{% translate "Telephone" %}</h6>
                </div>
                <div class="col-sm-8 text-secondary">{{evaluator.telephone}} </div>
            </div>
            <hr>
            <div class="row">
                <div class="col-sm-4">
                    <h6 class="mb-0">{% translate "Department" %}</h6>
                </div>
                <div class="col-sm-8 text-secondary"><a href="{% url 'org:department_detail' evaluator.department.pk %}">{{evaluator.department}}</a> </div>
            </div>
            <hr>
        </div>
    </div>
{% endblock %}

mscApplications/evaluator/templates/evaluator_profile_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load i18n %}
{% block title %}{% translate "Edit Profile" %}{% endblock title %}
{% block content %}
  <div class="card">
    <div class="card-header text-white msc-color">
      <h5 style="display: inline">{% translate "Edit Profile" %}</h5>
    </div>
    <div class="card-body">
      <form method="post">
        {% csrf_token %}
        {% crispy form  %}
        <button type="submit" class="btn btn-outline-success rounded-pill">{% translate "Submit" %}</button>
      </form>
    </div>
  </div>
{% endblock %}

mscApplications/evaluator/templates/evaluator_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load i18n %}
{% block title %}{% translate "Update Evaluator" %}{% endblock title %}

{% block content %}
  <div class="card">
    <form method="post">
      <div class="card-header msc-color text-white">
        <h5 style="display: inline">
          {% translate "Update Evaluator" %}
        </h5>
      </div>
      <div class="card-body">
        <div class="container">
          {% csrf_token %}
          {% crispy form %}
        </div>
      </div>
      <div class="card-footer msc-color">
        <button type="submit" class="btn btn-outline-light rounded-pill">{% translate "Submit" %}</button>
      </div>
    </form>
  </div>
{% endblock %}