mscApplications/applicant/urls.py
from django.urls import  path
from .views import *

app_name = 'applicant'
urlpatterns = [
    path('home', ApplicantHomeView.as_view(), name='applicant_home'),
    path('profile', ApplicantProfileDetailView.as_view(), name='applicant_profile'),
    path('profile/edit', ApplicantProfileUpdateView.as_view(), name='applicant_profile_edit'),
    path('<int:pk>/detail', ApplicantDetailView.as_view(), name='applicant_detail'),
    path('applications', ApplicantApplicationListView.as_view(), name='applicant_applications'),
]

mscApplications/institution/urls.py
from django.urls import  path
from .views import *

app_name = 'org'

urlpatterns = [
    path('institutions/<int:pk>/detail/', InstitutionDetailView.as_view(), name='institution_detail'),
    path('departments/<int:pk>/detail/', DepartmentDetailView.as_view(), name='department_detail'),
]

mscApplications/msc/urls.py
from django.urls import  path
from .views import *

app_name = 'msc'

urlpatterns = [
    path('calls', CallListView.as_view(), name='call_list'),
    path('calls/create', CallCreateView.as_view(), name='call_create'),
    path('calls/<int:pk>/detail', CallDetailView.as_view(), name='call_detail'),
    path('calls/<int:pk>/delete', CallDeleteView.as_view(), name='call_delete'),
    path('calls/<int:pk>/update', CallUpdateView.as_view(), name='call_update'),
    path('calls/<int:pk>/applications', ApplicationListView.as_view(), name='call_application_list'),
    path('calls/<int:pk>/new-application', ApplicationCreateView.as_view(), name='call_new_application'),
    path('calls/<int:call_pk>/applications/<int:pk>/admit', ApplicationAdmitView.as_view(), name='call_application_admit'),
    path('programmes', MscProgrammeListView.as_view(), name='msc_programme_list'),
    path('programmes/create', MscProgrammeCreateView.as_view(), name='msc_programme_create'),
    path('programmes/<int:pk>', MscProgrammeDetailView.as_view(), name='msc_programme_detail'),
    path('programmes/<int:pk>/edit', MscProgrammeUpdateView.as_view(), name='msc_programme_update'),
    path('programmes/<int:pk>/delete', MscProgrammeDeleteView.as_view(), name='msc_programme_delete'),
]

mscApplications/mscApplications/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from .views import HomeView


urlpatterns = [
    path("accounts/", include("allauth.urls")),
    path("users/", include("user_account.urls", namespace="user_account")),
    path(
        "applicant/",
        include(
            "applicant.urls",
            namespace="applicant",
        ),
    ),
    path(
        "evaluator/",
        include("evaluator.urls",
        namespace="evaluator",
        ),
    ),
    path(
        "secretary/",
        include("secretary.urls",
        namespace="secretary",
        ),
    ),
    path(
        "msc/",
        include("msc.urls",
        namespace="msc",
        ),

    ),
    path(
        "org/",
        include("institution.urls",
        namespace="org",
        ),

    ),
    path("", HomeView.as_view(), name='home'),
    path("admin/", admin.site.urls),
    path("i18n/", include("django_translation_flags.urls")),
]
if settings.DEBUG==True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mscApplications/msc/models.py
from django.db import models
from institution.models import Department
from django.utils.translation import gettext as _
from evaluator.models import Evaluator
from django.db import models
from applicant.models import Applicant,Reference
from .utils import application_upload
from django.core.validators import FileExtensionValidator

class MscProgramme(models.Model):
    title = models.CharField(_('Title'),max_length = 200)
    address = models.CharField(_('Address'),max_length=50)
    description=models.TextField(_('description'),null=True,blank=True)
    department=models.ForeignKey(Department,on_delete=models.CASCADE, verbose_name=_("Department"))

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _("MSC Programme")
        verbose_name_plural = _("MSC Programmes")

class MscFlow(models.Model):
    title = models.CharField(_('Title'),max_length = 200)
    msc_programme=models.ForeignKey(MscProgramme,on_delete=models.CASCADE,verbose_name=_("Msc Programme"))

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _("MSC Flow")
        verbose_name_plural = _("MSC Flows")


class Call(models.Model):
    title = models.CharField(_('Title'),max_length = 200)
    start_date=models.DateField(_('Start date'))
    end_date=models.DateField(_('End Date'))
    msc_programme=models.ForeignKey(MscProgramme,on_delete=models.CASCADE, verbose_name=_("Msc Programme"))
    evaluators = models.ManyToManyField(
        Evaluator, blank=False)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _("Call")
        verbose_name_plural = _("Calls")

class Application (models.Model):
    applicant=models.ForeignKey(Applicant,on_delete=models.CASCADE)
    call=models.ForeignKey(Call,on_delete=models.CASCADE)
    submission_date=models.DateField(_('Submission Date'),auto_now_add=True)
    comments=models.TextField(_('Comments'),null=True,blank=True)
    admitted=models.BooleanField(_('Admitted'),default=None,null=True,blank=True)
    reference=models.ForeignKey(Reference,on_delete=models.SET_NULL,null=True,blank=True)
    media_file = models.FileField(_('Media File'),upload_to=application_upload,validators=[FileExtensionValidator(allowed_extensions=['pdf'])])
    preferences = models.ManyToManyField(MscFlow,through='Preference',blank=True,related_name="waiting_applications")
    admitted_flow=models.ForeignKey(MscFlow,on_delete=models.CASCADE,blank=True,null=True,related_name="admitted_application")

    def __str__(self):
        return self.applicant.user.email+" application"

    class Meta:
        verbose_name = _("Application")
        verbose_name_plural = _("Applications")
        constraints = [
        models.UniqueConstraint(fields=['applicant', 'call'], name='unique call for applicant')
    ]
class Preference(models.Model):
    application = models.ForeignKey(Application, on_delete=models.CASCADE)
    flow = models.ForeignKey(MscFlow,on_delete=models.CASCADE)
    priority = models.PositiveIntegerField(_('Priority'),)

    class Meta:
        ordering = ["priority"]
        verbose_name = _("Priority")
        verbose_name_plural = _("Priorities")

    def __str__(self):
        return  self.flow.title

mscApplications/msc/views.py
from subprocess import call
from django.db.models import Q
from django.views.generic import ListView,DetailView,CreateView,UpdateView,DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse, reverse_lazy
from django.shortcuts import get_object_or_404
from django.http import FileResponse
from django.utils.translation import ugettext_lazy as _
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages

from extra_views import  CreateWithInlinesView,UpdateWithInlinesView, InlineFormSetFactory

from secretary.models import Secretary
from evaluator.models import Evaluator

from .models import *

from .filters import MscProgrammeFilter
from .forms import *

from utils.mixins import *
from utils import pdf_generator

import uuid
import datetime

# Applications
class ApplicationListView(LoginRequiredMixin,EvaluatorOrSecretaryRequiredMixin,UserPassesTestMixin,ListView):
    model=Application
    template_name= 'application/application_list.html'
    context_object_name='applications'

    def get_queryset(self):
        call = Call.objects.get(id=self.kwargs['pk'])
        applications= Application.objects.filter(call=call).order_by('-submission_date')
        return applications

    def test_func(self):
        call = Call.objects.get(id=self.kwargs['pk'])
        user = self.request.user
        if user.has_evaluator():
            if user.evaluator in call.evaluators.all():
                return True
        if user.has_secretary():
            if call.msc_programme.department==user.secretary.department:
                return True
        return False

    def get_context_data(self, **kwargs):
        context = super(ApplicationListView, self).get_context_data(**kwargs)
        context['call']=Call.objects.get(id=self.kwargs['pk'])
        return context


class ApplicationCreateView(LoginRequiredMixin,ApplicantRequiredMixin,ApplicantCompleteProfileMixin,CreateView):
    model=Application
    template_name='application/application_create.html'
    form_class=ApplicationForm

    def get_context_data(self, **kwargs):
        context = super(ApplicationCreateView, self).get_context_data(**kwargs)
        context['call'] =Call.objects.get(id=self.kwargs['pk'])
        return context

    def get_form(self, *args, **kwargs):
        form = super().get_form(*args, **kwargs)
        call=Call.objects.get(id=self.kwargs['pk'])
        if call.msc_programme.mscflow_set.all:
            form.fields['preferences'].required = True
        form.fields['preferences'].queryset = MscFlow.objects.filter(msc_programme=call.msc_programme)
        form.fields['reference'].queryset = Reference.objects.filter(applicant=self.request.user.applicant)
        form.fields['preferences'].label = _("Select flows by the order you prefer")
        return form

    def form_valid(self, form):
        application = form.save(commit=False)
        application.applicant=self.request.user.applicant
        application.call= get_object_or_404(Call, id=self.kwargs['pk'])
        if Application.objects.filter(applicant=application.applicant,call=application.call).exists():
            messages.warning(self.request, (_('You have already submitted an application for this call !')))
            return redirect('/msc/calls/'+str(self.kwargs['pk'])+'/detail')
        application.save()
        for index,flow_id in enumerate(self.request.POST.getlist('preferences')):
            application.preferences.add(int(flow_id), through_defaults={'priority': index+1})
        file_data=None
        if self.request.LANGUAGE_CODE =='en':
            file_data= pdf_generator.generate_applicant_app(self.request.user.applicant,application)
        else:
            file_data= pdf_generator.generate_applicant_app_to_greek(self.request.user.applicant,application)
        application.media_file.save(self.request.user.email+uuid.uuid4().hex[:6].upper()+".pdf", file_data, save=False)
        application.save()
        return FileResponse(application.media_file)


class ApplicationAdmitView(LoginRequiredMixin,EvaluatorOrSecretaryRequiredMixin,UserPassesTestMixin,SuccessMessageMixin,UpdateView):
    model=Application
    form_class=ApplicationAdmitForm
    template_name = 'application/application_admit.html'
    success_message = _('Application admitted !')

    def test_func(self):
        call = Call.objects.get(id=self.kwargs['call_pk'])
        user = self.request.user
        if user.has_evaluator():
            if user.evaluator in call.evaluators.all():
                return True
        if user.has_secretary():
            if call.msc_programme.department==user.secretary.department:
                return True
        return False

    def get_form(self, *args, **kwargs):
        form = super().get_form(*args, **kwargs)
        form.fields['admitted'].label = ""
        form.fields['admitted_flow'].queryset = self.object.preferences.all()
        form.fields['admitted_flow'].label = ""
        return form

    def get_success_url(self):
        return reverse('msc:call_application_list',kwargs={'pk':self.get_object().call.id} )


# MSC Programmes
class MscProgrammeListView(ListView):
    model=MscProgramme
    template_name='msc_programme/msc_programme_list.html'
    context_object_name='programmes'
    paginate_by = 6

    def get_queryset(self):
        qs = self.model.objects.all().order_by('id')
        programme_filtered_list = MscProgrammeFilter(self.request.GET, queryset=qs)
        return programme_filtered_list.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        queryset = self.get_queryset()
        filter = MscProgrammeFilter(self.request.GET, queryset)
        context['filter'] = filter
        return context


class MscProgrammeDetailView(DetailView):
    model=MscProgramme
    template_name='msc_programme/msc_programme_detail.html'
    context_object_name='programme'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        calls = Call.objects.filter(Q(end_date__gte=datetime.datetime.now())&Q(start_date__lte=datetime.datetime.now())).filter(msc_programme__id=self.kwargs['pk'])
        context['calls']=calls
        return context


class MSCFlowInline(InlineFormSetFactory):
    model = MscFlow
    form_class=MscFlowForm
    factory_kwargs = {'extra': 1}


class MscProgrammeCreateView(SuccessMessageMixin,SecretaryRequiredMixin,CreateWithInlinesView):
    model=MscProgramme
    form_class=MscProgrammeForm
    inlines = [ MSCFlowInline,]
    template_name='msc_programme/msc_programme_create.html'
    success_message = _('MSC Programme created !')
    success_url=reverse_lazy('secretary:secretary_programmes')

    def form_valid(self, form):
        form.instance.department=self.request.user.secretary.department
        return super().form_valid(form)


class MscProgrammeUpdateView(SuccessMessageMixin,SecretaryRequiredMixin,UserPassesTestMixin,UpdateWithInlinesView):
    model=MscProgramme
    form_class=MscProgrammeForm
    inlines = [ MSCFlowInline,]
    template_name='msc_programme/msc_programme_update.html'
    success_message = _('MSC Programme updated !')
    success_url=reverse_lazy('secretary:secretary_programmes')

    def test_func(self):
        user = self.request.user
        if user.has_secretary():
            if self.get_object().department==user.secretary.department:
                return True
        return False

    def form_valid(self, form):
        form.instance.department=self.request.user.secretary.department
        return super().form_valid(form)


class MscProgrammeDeleteView(LoginRequiredMixin,SecretaryRequiredMixin,UserPassesTestMixin,DeleteView):
    model=MscProgramme

    def test_func(self):
        user = self.request.user
        if user.has_secretary():
            if self.get_object().department==user.secretary.department:
                return True
        return False


    def get_success_url(self):
        messages.success(self.request, (_('MSC Programme deleted.')))
        return reverse('secretary:secretary_programmes')

#Calls
class CallListView(ListView):
    model = Call
    template_name = 'call/call_list.html'
    context_object_name = 'calls'
    paginate_by = 4

    def get_queryset(self) :
        queryset = Call.objects.filter(Q(end_date__gte=datetime.datetime.now())&Q(start_date__lte=datetime.datetime.now()))
        return queryset


class CallDetailView(DetailView):
    model = Call
    template_name = 'call/call_detail.html'
    context_object_name = 'call'


class CallCreateView(LoginRequiredMixin,SuccessMessageMixin,SecretaryRequiredMixin,CreateView):
    template_name='call/call_create.html'
    success_message = _('Call created !')
    success_url=reverse_lazy('secretary:secretary_calls')
    form_class=CallForm

    def get_form(self, *args, **kwargs):
        form = super().get_form(*args, **kwargs)
        form.fields['evaluators'].queryset = Evaluator.objects.filter(department=self.request.user.secretary.department)
        form.fields['msc_programme'].queryset = MscProgramme.objects.filter(department=self.request.user.secretary.department)
        return form


class CallUpdateView(LoginRequiredMixin,SuccessMessageMixin,SecretaryRequiredMixin,UserPassesTestMixin,UpdateView):
    model=Call
    form_class=CallForm
    template_name='call/call_update.html'
    success_message = _('Call updated !')
    success_url=reverse_lazy('secretary:secretary_calls')

    def test_func(self):
        user = self.request.user
        if user.has_secretary():
            if self.get_object().msc_programme.department==user.secretary.department:
                return True
        return False


    def get_form(self, *args, **kwargs):
        form = super().get_form(*args, **kwargs)
        form.fields['evaluators'].queryset = Evaluator.objects.filter(department=self.request.user.secretary.department)

mscApplications/msc/templates/application_create.html
{% extends 'base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}
{% load static %}

{% block extra_css %}
  <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
  <style>
    #id_preferences{
      width: 100% !important;
    }
  </style>
{% endblock %}

{% block title %}{% translate "New Application" %} {% endblock title %}
{% block content %}

  <div class="card">
    <div class="card-header msc-color text-white">
      <h5 style="display: inline">
        {% translate "New Application for" %} {{call}}
      </h5>
    </div>
    <div class="card-body">
      <form method="post">
          {% csrf_token %}
          {{form | crispy}}
          <button type="submit" class="btn btn msc-color text-white">{% translate "Submit" %}</button>

      </form>
    </div>
  </div>
{% endblock %}
{% block javascript %}
  <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
  <script type="text/javascript">
      $('.selectmultiple').select2();
        $('.selectmultiple').on('select2:select', function(e){
          var elm = e.params.data.element;
          $elm = jQuery(elm);
          $t = jQuery(this);
          $t.append($elm);
          $t.trigger('change.select2');
      });
  </script>
{% endblock %}

mscApplications/msc/templates/call_applications.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block title %} {% translate "Applications" %}{% endblock title %}
{% block extra_css %}
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.21/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.15/css/jquery.dataTables.min.css"></link>
{% endblock %}
{% block content %}
        <div class="card">
            <div class="card-header msc-color text-white">
               <h5 style="display: inline">{% translate "Applications" %}</h5>
            </div>
            <div class="card-body table-responsive">
                <table id="datatable" class="table align-items-center table-flush">
                    <thead class="bg-light">
                        <tr>
                            <th scope="col">{% translate "Applicant" %}</th>
                            <th scope="col">{% translate "Submission Date" %}</th>
                            <th scope="col">{% translate "Admitted" %}</th>
                            <th scope="col">{% translate "Actions" %}</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for app in applications %}
                            <tr>
                                <td><a href="{% url 'applicant:applicant_detail'  app.applicant.pk  %}">{{app.applicant}}</a></td>
                                <td>{{app.submission_date}}</td>
                                <td>
                                    {% if app.admitted == None %}
                                        {% translate "Pending" %}
                                    {% elif app.admitted == True %}
                                        {% translate "Yes" %}
                                    {% else %}
                                        {% translate "No" %}
                                    {% endif %}
                                </td>
                                <td>
                                    <a class="btn msc-color text-white" href="{% url 'msc:call_application_admit' app.pk  %}">{% translate "Admit" %}</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
        </div>
    </div>

{% endblock content %}
{% block javascript %}
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js"></script>
    <script type="text/javascript">
        $('#datatable').DataTable({
            "ordering" : false,
        });
    </script>
{% endblock %}

mscApplications/msc/templates/msc_programme_create.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% load bootstrap5 %}

{% block title %}{% translate "New MSC Programme " %} {% endblock title %}
{% block content %}

  <div class="card">
    <div class="card-header msc-color text-white">
      <h5 style="display: inline">
        {% translate "New MSC Programme " %}
      </h5>
    </div>
    <div class="card-body">
      <ul class="nav nav-pills flex-column flex-sm-row" id="myTab" role="tablist">
        <li class="nav-item" role="presentation">
          <a
            class="flex-sm-fill text-sm-center nav-link active"
            id="programme-tab"
            data-bs-toggle="tab"
            href="#programme"
            role="tab"
            aria-controls="programme"
            aria-selected="false"
            >{% translate "MSC Programme" %}</a
          >
        </li>
        <li class="nav-item " role="presentation">
          <a
            class="flex-sm-fill text-sm-center nav-link"
            id="flows-tab"
            data-bs-toggle="tab"
            href="#flows"
            role="tab"
            aria-controls="flows"
            aria-selected="false"
            >{% translate "Msc Flows" %}</a
          >
        </li>
      </ul>
      <br>
      <form method="post">
        <div class="tab-content" id="myTabContent">
        <div
          class="tab-pane fade show active"
          id="programme"
          role="tabpanel"
          aria-labelledby="programme-tab"
        >
          <div class="container">
            {% csrf_token %}
            {% bootstrap_form form layout='horizontal' %}
          </div>
        </div>
        <div  
          class="tab-pane fade "
          id="flows"
          role="tabpanel"
          aria-labelledby="flows-tab"
        >
          {% for formset in inlines %}
            {{ formset.management_form }}
            <div class="row" id="{{formset.prefix}}">
              {% for form in formset.forms %}
                <div class="col-12">
                  {% bootstrap_form form layout='horizontal' %}
                </div>
                
              {% endfor %}
            </div>
            <br>
            <input class="btn-sm btn-outline " type="button" value="Add More" onclick = "add_more('mscflow_set');" >
            <div id="empty_form" style="display:none">
              <div class="col-12">
                {% bootstrap_form formset.empty_form layout='horizontal' %}
              </div>
            </div>
            <hr>
          {% endfor%}
        </div>
          <button type="submit" class="btn btn msc-color text-white">{% translate "Submit" %}</button>
        </div>
        </form>
    </div>
  </div>
{% endblock %}
{% block javascript %}
  <script type="text/javascript">
    function add_more(form) {
      var form_idx = $('#id_'+form+'-TOTAL_FORMS').val();
      $('#'+form).append($('#empty_form').html().replace(/__prefix__/g, form_idx));
      $('#id_'+form+'-TOTAL_FORMS').val(parseInt(form_idx) + 1);
    }
  </script>
{% endblock %}

mscApplications/msc/templates/msc_programme_detail.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block title %} {{ programme.title }}{% endblock title %}

{% block content %}
    <div class="row">
        <div class="col-12 col-md-9">

            <div class="card">
                <div class="card-header msc-color text-white">
                    <h5 style="display: inline">
                        {{programme.title}}
                    </h5>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-12 col-md-6">
                            <p><strong>{% translate "Country" %}:</strong>
                                {{programme.country}}
                            </p>
                            <p><strong>{% translate "City" %}:</strong>
                                {{programme.city}}
                            </p>
                            <p><strong>{% translate "Address" %}:</strong>
                                {{programme.address}}
                            </p>
                            <p><strong>{% translate "Pobox" %}:</strong> {{programme.pobox }}</p>
                            <p><strong>{% translate "Telephone" %}:</strong> {{programme.telephone }}</p>
                        </div>
                        <div class="col-12 col-md-6">
                            <p><strong>{% translate "Department" %}:</strong>
                                <a href="{% url 'org:department_detail' programme.department.pk %}"> {{programme.department}}</a>
                            </p>
                            <p><strong>{% translate "Institution" %}:</strong>
                                <a href="{% url 'org:institution_detail' programme.department.institution.pk %}"> {{programme.department.institution}}</a>
                            </p>
                            <p><strong>{% translate "Flows" %} :</strong></p>
                            {% for flow in programme.mscflow_set.all %}
                                <p><strong>{{forloop.counter}} : </strong>{{flow.title}}</p>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% if programme.call_set.all %}
            <div class="col-12 col-md-3">
                <div class="card">
                    <div class="card-header msc-color text-white">
                        <h5 style="display: inline">
                            {% translate "Open Calls" %}
                        </h5>
                    </div>
                    <div class="card-body">
                        <div class="list-group">
                            {% for call in programme.call_set.all %}
                                <a href="{% url 'msc:call_detail' call.pk %}" class="list-group-item list-group-item-action" >
                                    {{call.title}}
                                </a>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        {% endif %}
    </div>

{% endblock %}

mscApplications/msc/templates/msc_programme_list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% load i18n %}

{% block title %} {% translate "MSC Programmes" %} {% endblock title %}


{% block content %}
    <div class="d-grid gap-2 text-center">
        <div class="card card-body header-color text-white">
            <button class="btn btn-link text-white" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample"><i class="fs-4 bi bi-search"></i>{% translate 'Search' %}</button>
        </div>
        <div class="collapse" id="collapseExample">
            <form class="card card-body" action="" method="get">
                {{ filter.form | crispy }}
                <input class="btn msc-color text-white" type="submit" />
            </form>
        </div>
    </div>

    <br><br>
    <figure class="text-center card card-body header-color text-white">
        <blockquote class="blockquote">
            <p>{% translate 'MSC Programmes' %}</p>
        </blockquote>
    </figure>

    <div class="row">
        {% for obj in filter.qs %}
            <div class="col-12 col-md-6">
                <div class="card hover">
                    <div class="card-header header-color text-white">
                        <h5 style="display: inline">
                            {{obj.title}}
                        </h5>
                    </div>
                    <div class="card-body msc-color text-white">
                        <div class="row text-center">
                            <p><strong>{% translate "Institution" %}:</strong>
                                {{obj.department.institution}}
                            </p>
                            <p><strong>{% translate "Department" %}:</strong>
                                {{obj.department}}
                            </p>
                            <p><strong>{% translate "Flows" %} :</strong></p>
                            {% for flow in obj.mscflow_set.all %}
                                <p><strong>{{forloop.counter}} : </strong>{{flow.title}}</p>
                            {% endfor %}
                        </div>
                        <a href="{% url 'msc:msc_programme_detail' obj.pk %}" class="stretched-link"></a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}