mscApplications/evaluator/urls.py
from django.urls import  path
from .views import *

app_name = 'evaluator'

urlpatterns = [
    path('home', EvaluatorHomeView.as_view(), name='evaluator_home'),
    path('profile', EvaluatorProfileDetailView.as_view(), name='evaluator_profile'),
    path('profile/edit', EvaluatorProfileUpdateView.as_view(), name='evaluator_profile_edit'),
    path('calls', EvaluatorCallListView.as_view(),name='evaluator_calls'),
    path('create', EvaluatorCreateView.as_view(),name='evaluator_create'),
    path('<int:pk>/delete', EvaluatorDeleteView.as_view(),name='evaluator_delete'),
    path('<int:pk>/update', EvaluatorUpdateView.as_view(),name='evaluator_update'),

]

mscApplications/institution/urls.py
from django.urls import  path
from .views import *

app_name = 'org'

urlpatterns = [
    path('institutions/<int:pk>/detail/', InstitutionDetailView.as_view(), name='institution_detail'),
    path('departments/<int:pk>/detail/', DepartmentDetailView.as_view(), name='department_detail'),
]

mscApplications/msc/urls.py
from django.urls import  path
from .views import *

app_name = 'msc'

urlpatterns = [
    path('calls', CallListView.as_view(), name='call_list'),
    path('calls/create', CallCreateView.as_view(), name='call_create'),
    path('calls/<int:pk>/detail', CallDetailView.as_view(), name='call_detail'),
    path('calls/<int:pk>/delete', CallDeleteView.as_view(), name='call_delete'),
    path('calls/<int:pk>/update', CallUpdateView.as_view(), name='call_update'),
    path('calls/<int:pk>/applications', ApplicationListView.as_view(), name='call_application_list'),
    path('calls/<int:pk>/new-application', ApplicationCreateView.as_view(), name='call_new_application'),
    path('calls/<int:call_pk>/applications/<int:pk>/admit', ApplicationAdmitView.as_view(), name='call_application_admit'),
    path('programmes', MscProgrammeListView.as_view(), name='msc_programme_list'),
    path('programmes/create', MscProgrammeCreateView.as_view(), name='msc_programme_create'),
    path('programmes/<int:pk>', MscProgrammeDetailView.as_view(), name='msc_programme_detail'),
    path('programmes/<int:pk>/edit', MscProgrammeUpdateView.as_view(), name='msc_programme_update'),
    path('programmes/<int:pk>/delete', MscProgrammeDeleteView.as_view(), name='msc_programme_delete'),
]

mscApplications/mscApplications/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from .views import HomeView


urlpatterns = [
    path("accounts/", include("allauth.urls")),
    path("users/", include("user_account.urls", namespace="user_account")),
    path(
        "applicant/",
        include(
            "applicant.urls",
            namespace="applicant",
        ),
    ),
    path(
        "evaluator/",
        include("evaluator.urls",
        namespace="evaluator",
        ),
    ),
    path(
        "secretary/",
        include("secretary.urls",
        namespace="secretary",
        ),
    ),
    path(
        "msc/",
        include("msc.urls",
        namespace="msc",
        ),

    ),
    path(
        "org/",
        include("institution.urls",
        namespace="org",
        ),

    ),
    path("", HomeView.as_view(), name='home'),
    path("admin/", admin.site.urls),
    path("i18n/", include("django_translation_flags.urls")),
]
if settings.DEBUG==True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mscApplications/secretary/urls.py
from django.urls import  path
from .views import *

app_name = 'secretary'

urlpatterns = [
    path('home', SecretaryHome.as_view(), name='secretary_home'),
     path('profile', SecretaryProfileDetailView.as_view(), name='secretary_profile'),
    path('profile/edit', SecretaryProfileUpdateView.as_view(), name='secretary_profile_edit'),
    path('calls', SecretaryCallListView.as_view(), name='secretary_calls'),
    path('programmes', SecretaryMscProgrammeListView.as_view(), name='secretary_programmes'),
    path('evaluators', SecretaryEvaluatorListView.as_view(), name='secretary_evaluators'),
]

mscApplications/user_account/urls.py
from django.conf.urls import url
from django.urls import path, include
from .views import *
from django.contrib.auth import views as auth_views

app_name = "user_account"


urlpatterns = [
    path("check", CheckUser.as_view(), name="check-user"),
    path("change-password", ChangePasswordView.as_view(), name="user_change_password"),
]

mscApplications/msc/models.py
from django.db import models
from institution.models import Department
from django.utils.translation import gettext as _
from evaluator.models import Evaluator
from django.db import models
from applicant.models import Applicant,Reference
from .utils import application_upload
from django.core.validators import FileExtensionValidator

class MscProgramme(models.Model):
    title = models.CharField(_('Title'),max_length = 200)
    address = models.CharField(_('Address'),max_length=50)
    description=models.TextField(_('description'),null=True,blank=True)
    department=models.ForeignKey(Department,on_delete=models.CASCADE, verbose_name=_("Department"))

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _("MSC Programme")
        verbose_name_plural = _("MSC Programmes")

class MscFlow(models.Model):
    title = models.CharField(_('Title'),max_length = 200)
    msc_programme=models.ForeignKey(MscProgramme,on_delete=models.CASCADE,verbose_name=_("Msc Programme"))

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _("MSC Flow")
        verbose_name_plural = _("MSC Flows")


class Call(models.Model):
    title = models.CharField(_('Title'),max_length = 200)
    start_date=models.DateField(_('Start date'))
    end_date=models.DateField(_('End Date'))
    msc_programme=models.ForeignKey(MscProgramme,on_delete=models.CASCADE, verbose_name=_("Msc Programme"))
    evaluators = models.ManyToManyField(
        Evaluator, blank=False)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _("Call")
        verbose_name_plural = _("Calls")

class Application (models.Model):
    applicant=models.ForeignKey(Applicant,on_delete=models.CASCADE)
    call=models.ForeignKey(Call,on_delete=models.CASCADE)
    submission_date=models.DateField(_('Submission Date'),auto_now_add=True)
    comments=models.TextField(_('Comments'),null=True,blank=True)
    admitted=models.BooleanField(_('Admitted'),default=None,null=True,blank=True)
    reference=models.ForeignKey(Reference,on_delete=models.SET_NULL,null=True,blank=True)
    media_file = models.FileField(_('Media File'),upload_to=application_upload,validators=[FileExtensionValidator(allowed_extensions=['pdf'])])
    preferences = models.ManyToManyField(MscFlow,through='Preference',blank=True,related_name="waiting_applications")
    admitted_flow=models.ForeignKey(MscFlow,on_delete=models.CASCADE,blank=True,null=True,related_name="admitted_application")

    def __str__(self):
        return self.applicant.user.email+" application"

    class Meta:
        verbose_name = _("Application")
        verbose_name_plural = _("Applications")
        constraints = [
        models.UniqueConstraint(fields=['applicant', 'call'], name='unique call for applicant')
    ]
class Preference(models.Model):
    application = models.ForeignKey(Application, on_delete=models.CASCADE)
    flow = models.ForeignKey(MscFlow,on_delete=models.CASCADE)
    priority = models.PositiveIntegerField(_('Priority'),)

    class Meta:
        ordering = ["priority"]
        verbose_name = _("Priority")
        verbose_name_plural = _("Priorities")

    def __str__(self):
        return  self.flow.title

mscApplications/secretary/models.py
from django.db import models
from institution.models import Department
from utils.validators import telephone_validator
from django.utils.translation import gettext as _

from django.conf import settings


# Create your models here.
class Secretary(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL,related_name='secretary', on_delete=models.CASCADE,primary_key=True)
    department = models.ForeignKey(Department,on_delete=models.SET_NULL,null=True)
    telephone = models.CharField(_('Telephone'),max_length = 10,validators=[telephone_validator])

    class Meta:
        verbose_name = _("Secretary")
        verbose_name_plural = _("Secretaries")

mscApplications/secretary/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Row, Column
from django.utils.translation import gettext_lazy as _
from .models import Secretary

class SecretaryForm(forms.ModelForm):
    first_name = forms.CharField(max_length=30, label=_('First Name'))
    last_name = forms.CharField(max_length=30, label=_('Last Name'))
    class Meta:
        model = Secretary
        fields = ("first_name", "last_name", "telephone")

    def __init__(self, *args, **kwargs):
        super(SecretaryForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.layout = Layout(
            Row(
                Column("first_name", css_class="form-group col-md-6 mb-0"),
                Column("last_name", css_class="form-group col-md-6 mb-0"),
                css_class="form-row",
            ),
            "telephone",
        )

mscApplications/secretary/views.py
from django.views.generic import DetailView,ListView, UpdateView,TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.translation import ugettext_lazy as _
from msc.models import Call, MscProgramme
from evaluator.models import Evaluator
from .models import *
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from .forms import *
from utils.mixins import SecretaryRequiredMixin
# Create your views here.

class SecretaryHome(LoginRequiredMixin,SecretaryRequiredMixin,TemplateView):
    template_name = 'secretary_home.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['department']=self.request.user.secretary.department
        return context


class SecretaryProfileDetailView(LoginRequiredMixin,SecretaryRequiredMixin,DetailView):
    model=Secretary
    context_object_name = 'secretary'
    template_name = 'secretary_profile.html'

    def get_object(self):
        return self.request.user.secretary


class SecretaryProfileUpdateView(LoginRequiredMixin,SuccessMessageMixin,SecretaryRequiredMixin,UpdateView):
    model = Secretary
    form_class=SecretaryForm
    template_name = 'secretary_profile_edit.html'
    success_url = reverse_lazy('secretary:secretary_profile')
    success_message = _('Your profile has been updated.')

    def get_form(self, *args, **kwargs):
        form = super().get_form(*args, **kwargs)
        form.fields['first_name'].initial = self.request.user.first_name
        form.fields['last_name'].initial = self.request.user.last_name
        return form

    def form_valid(self,form):
        user=form.instance.user
        user.first_name=form.cleaned_data['first_name']
        user.last_name=form.cleaned_data['last_name']
        user.save()
        return super().form_valid(form)

    def get_object(self):
        return self.request.user.secretary

class SecretaryMscProgrammeListView(LoginRequiredMixin,SecretaryRequiredMixin,ListView):
    models =MscProgramme
    template_name = 'secretary_msc_programme_list.html'
    context_object_name='programmes'

    def get_queryset(self):
        return MscProgramme.objects.filter(department=self.request.user.secretary.department)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['department']=self.request.user.secretary.department
        return context

class SecretaryEvaluatorListView(LoginRequiredMixin,SecretaryRequiredMixin,ListView):
    models =Evaluator
    template_name = 'secretary_evaluator_list.html'
    context_object_name='evaluators'

    def get_queryset(self):
        return Evaluator.objects.filter(department=self.request.user.secretary.department)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['department']=self.request.user.secretary.department
        return context


class SecretaryCallListView(LoginRequiredMixin,SecretaryRequiredMixin,ListView):
    models =Call
    template_name = 'secretary_call_list.html'
    context_object_name='calls'

    def get_queryset(self):
        return Call.objects.filter(msc_programme__department=self.request.user.secretary.department)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['department']=self.request.user.secretary.department
        return context

mscApplications/secretary/templates/secretary_call_list.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block title %}{% translate "Secretary Calls" %}{% endblock title %}

{% block content %}


    <div class="card">
        <div class="card-header msc-color text-white">
            <h5 style="display: inline">
                {{user.secretary.department}} {% translate "Calls" %}
            </h5>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="cols-12 col-sm-6 text-center">
                    <p><strong>{% translate "Country" %}:</strong>
                        {{department.country}}
                    </p>
                    <p><strong>{% translate "City" %}:</strong>
                        {{department.city}}
                    </p>
                    <p><strong>{% translate "Address" %}:</strong>
                        {{department.address}}
                    </p>
                </div>
                <div class="cols-12 col-sm-6 text-center">
                    <p><strong>{% translate "Pobox" %}:</strong> {{department.pobox }}</p>
                    <p><strong>{% translate "Telephone" %}:</strong> {{department.telephone }}</p>
                    <p><strong>{% translate "Institution" %}:</strong> <a href="{% url 'org:institution_detail' department.institution.pk %}" >{{department.institution }}</a></p>
                </div>
            </div>
            {% if calls %}
                <div class="accordion accordion-flush" id="accordionFlushRefs">
                    {% for call in calls %}
                        <div class="accordion-item">
                            <h2 class="accordion-header" id="flush-heading{{forloop.counter}}">
                            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapse{{forloop.counter}}" aria-expanded="false" aria-controls="flush-collapse{{forloop.counter}}">
                                        {{call.title}}
                                </button>
                            </h2>
                            <div id="flush-collapse{{forloop.counter}}" class="accordion-collapse collapse" aria-labelledby="flush-heading{{forloop.counter}}" data-bs-parent="#accordionFlushPhds">
                                <div class="accordion-body">
                                    <div class="row">
                                        <div class="cols-12 col-sm-6">
                                            <p><strong>{% translate "Start Date" %}:</strong>
                                                {{call.start_date}}
                                            </p>
                                            <p><strong>{% translate "End Date" %}:</strong>
                                                {{call.end_date}}
                                            </p>
                                        </div>
                                        <div class="cols-12 col-sm-6">
                                            <p><strong>{% translate "MSC Programme" %}:</strong>
                                                {{call.msc_programme}}
                                            </p>
                                        </div>
                                    </div>
                                    <p>
                                        <a href="{% url 'msc:call_update' call.pk %}"   class="btn msc-color text-light"><i class="bi bi-pencil-square"></i></a>
                                        <button  data-bs-toggle="modal" data-bs-target="#exampleModal" onclick="return deletecall('{{call.pk}}','{{call.title}}');" class="btn msc-color text-light"><i class="bi bi-trash"></i></button>
                                        <a href="{% url 'msc:call_detail' call.pk %}" class="btn msc-color text-light"><i class="bi bi-eye"></i></a>
                                        <a href="{% url 'msc:call_application_list' call.pk %}" class="btn msc-color text-light"><i class="bi bi-card-checklist"></i></a>

                                    </p>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            {% else %}
                <div class="row">
                    <div class="col col-12">
                        <div class="alert alert-danger">{% translate "No Calls found " %}</div>
                    </div>
                </div>
            {% endif %}
        </div>
        <div class="card-footer msc-color">
            <span class="float-start"><a href="{% url 'msc:call_create' %}" class="btn btn-outline-light rounded-pill">{% translate "Create Call" %}</a></span>

        </div>
    </div>
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel"></h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    {% translate "Are you sure you want to delete this Call ?" %}
                </div>
                <div class='modal-footer'>
                    <form name="myform" method='POST' action='' >
                        {% csrf_token %}
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <button type='submit' class='btn btn-danger'>Delete</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block javascript %}
<script>
   function deletecall(id,title){
        let action="/msc/calls/"+id+"/delete";
        document.myform.action = action;
        var div = document.getElementById('exampleModalLabel');
        div.innerHTML = '{% translate "Delete" %} '+title;
    }
</script>

{% endblock%}

mscApplications/secretary/templates/secretary_home.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block title %}{% translate "Secretary Dashboard" %}{% endblock title %}

{% block content %}
    <div class="row">
        <div class="col-12 col-sm-4">
            <div class="card">
                <div class="card-header msc-color text-white">
                    <h5 style="display: inline">
                        {% translate "Secretary Profile" %}
                    </h5>
                </div>
                <div class="card-body">
                    <p><strong>{% translate "Email" %}:</strong>
                        {{user.email}}
                    </p>
                    <p><strong>{% translate "Fisrt Name" %}:</strong>
                        {{user.first_name}}
                    </p>
                    <p><strong>{% translate "Last Name" %}:</strong> {{user.last_name }}</p>
                </div>
            </div>
        </div>
        <div class="col-12 col-sm-8">
            <div class="card">
                <div class="card-header msc-color text-white">
                    <h5 style="display: inline">
                        {{department.title}}
                    </h5>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-12 col-sm-6">
                            <p><strong>{% translate "Country" %}:</strong>
                                {{department.country}}
                            </p>
                            <p><strong>{% translate "City" %}:</strong>
                                {{department.city}}
                            </p>
                            <p><strong>{% translate "Address" %}:</strong>
                                {{department.address}}
                            </p>
                        </div>
                        <div class="col-12 col-sm-6">
                            <p><strong>{% translate "Pobox" %}:</strong> {{department.pobox }}</p>
                            <p><strong>{% translate "Telephone" %}:</strong> {{department.telephone }}</p>
                            <p><strong>{% translate "Institution" %}:</strong> <a href="{% url 'org:institution_detail' department.institution.pk %}" >{{department.institution }}</a></p>
                        </div>
                    </div>
                    <br>
                    <p>
                        <a href="{% url 'secretary:secretary_programmes' %}" class="btn btn-outline-success rounded-pill">{% translate "MSC Programmes" %}</a>
                        <a href="{% url 'secretary:secretary_calls' %}" class="btn btn-outline-success rounded-pill">{% translate "Calls" %}</a>
                        <a href="{% url 'secretary:secretary_evaluators' %}" class="btn btn-outline-success rounded-pill">{% translate "Evaluators" %}</a>

                    </p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

mscApplications/secretary/templates/secretary_msc_programme_list.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block title %}{% translate "Secretary Programmes" %}{% endblock title %}

{% block content %}
    <div class="card">
        <div class="card-header msc-color text-white">
            <h5 style="display: inline">
                {{department.title}} {% translate "MSC Programmes" %}
            </h5>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="cols-12 col-sm-6 text-center">
                    <p><strong>{% translate "Country" %}:</strong>
                        {{department.country}}
                    </p>
                    <p><strong>{% translate "City" %}:</strong>
                        {{department.city}}
                    </p>
                    <p><strong>{% translate "Address" %}:</strong>
                        {{department.address}}
                    </p>
                </div>
                <div class="cols-12 col-sm-6 text-center">
                    <p><strong>{% translate "Pobox" %}:</strong> {{department.pobox }}</p>
                    <p><strong>{% translate "Telephone" %}:</strong> {{department.telephone }}</p>
                    <p><strong>{% translate "Institution" %}:</strong> <a href="{% url 'org:institution_detail' department.institution.pk %}" >{{department.institution }}</a></p>
                </div>
            </div>
            {% if department.mscprogramme_set.all %}
                <div class="accordion accordion-flush" id="accordionFlushRefs">
                    {% for msc in department.mscprogramme_set.all %}
                        <div class="accordion-item">
                            <h2 class="accordion-header" id="flush-heading{{forloop.counter}}">
                            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapse{{forloop.counter}}" aria-expanded="false" aria-controls="flush-collapse{{forloop.counter}}">
                                        {{msc.title}}
                                </button>
                            </h2>
                            <div id="flush-collapse{{forloop.counter}}" class="accordion-collapse collapse" aria-labelledby="flush-heading{{forloop.counter}}" data-bs-parent="#accordionFlushPhds">
                                <div class="accordion-body">
                                    <p>
                                        {{msc.description |truncatewords:50 }}
                                    </p>
                                    <p><strong>{% translate "Address" %}:</strong>
                                        {{msc.address}}
                                    </p>
                                    <p>
                                        <a href="{% url 'msc:msc_programme_update' msc.pk %}"   class="btn msc-color text-light"><i class="bi bi-pencil-square"></i></a>
                                        <button  data-bs-toggle="modal" data-bs-target="#exampleModal" onclick="return deleteprogramme('{{msc.pk}}','{{msc.title}}');" title="Delete project" class="btn msc-color text-light"><i class="bi bi-trash"></i></button>
                                        <a href="{% url 'msc:msc_programme_detail' msc.pk %}" class="btn msc-color text-light"><i class="bi bi-eye"></i></a>
                                    </p>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            {% else %}
                <div class="row">
                    <div class="col col-12">
                        <div class="alert alert-danger">{% translate "No MSC Programmes found " %}</div>
                    </div>
                </div>
            {% endif %}
        </div>
        <div class="card-footer msc-color">
            <span class="float-start"><a href="/msc/programmes/create" class="btn btn-outline-light rounded-pill">{% translate "Create MSC Programme" %}</a></span>

        </div>
    </div>
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel"></h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    {% translate "Are you sure you want to delete this MSC Programme ?" %}
                </div>
                <div class='modal-footer'>
                    <form name="myform" method='POST' action='' >
                        {% csrf_token %}
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <button type='submit' class='btn btn-danger'>Delete</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block javascript %}
<script>
   function deleteprogramme(id,title){
        let action="/msc/programmes/"+id+"/delete";
        document.myform.action = action;
        var div = document.getElementById('exampleModalLabel');
        div.innerHTML = '{% translate "Delete" %} '+title;
    }
</script>
{% endblock%}

mscApplications/secretary/templates/secretary_profile.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block title %}{% translate "Profile" %} {% endblock title %}
{% block content %}

    <div class="row">
        <div class="col-md-3 text-center">
            <div class="profile-image">
                <i class="bi bi-person-circle big-icon"></i>
            </div>
            <h3>{% translate "Actions" %} :</h3>
            <a class="btn btn-outline-success rounded-pill"  href="{% url 'secretary:secretary_profile_edit' %}">{% translate "Edit Profile" %}</a>
            <div style="padding-top:10px;">
                <a class="btn btn-outline-success rounded-pill" href="{% url 'user_account:user_change_password' %}">{% translate "Change Password" %}</a>
            </div>
        </div>
        <div class="col-md-9">
            <br>
            <div class="profile-head">

                <h6>{{secretary.user.email}}</h6>

            </div>
            <br><br>
            <div class="row">
                <div class="col-sm-4">
                    <h6 class="mb-0">{% translate "First Name" %}</h6>
                </div>
                <div class="col-sm-8 text-secondary">{{secretary.user.first_name}}  </div>
            </div>
            <hr>
            <div class="row">
                <div class="col-sm-4">
                    <h6 class="mb-0">{% translate "Last Name" %}</h6>
                </div>
                <div class="col-sm-8 text-secondary">{{secretary.user.last_name}}  </div>
            </div>
            <hr>
            <div class="row">
                <div class="col-sm-4">
                    <h6 class="mb-0">{% translate "Telephone" %}</h6>
                </div>
                <div class="col-sm-8 text-secondary">{{secretary.telephone}} </div>
            </div>
            <hr>
            <div class="row">
                <div class="col-sm-4">
                    <h6 class="mb-0">{% translate "Department" %}</h6>
                </div>
                <div class="col-sm-8 text-secondary"><a href="{% url 'org:department_detail' secretary.department.pk %}">{{secretary.department}}</a> </div>
            </div>
            <hr>
        </div>
    </div>
{% endblock %}

mscApplications/secretary/templates/secretary_profile_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load i18n %}
{% block title %}{% translate "Edit Profile" %}{% endblock title %}
{% block content %}
  <div class="card">
    <div class="card-header text-white msc-color">
      <h5 style="display: inline">{% translate "Edit Profile" %}</h5>
    </div>
    <div class="card-body">
      <form method="post">
        {% csrf_token %}
        {% crispy form  %}
        <button type="submit" class="btn msc-color text-white rounded-pill">{% translate "Submit" %}</button>
      </form>
    </div>
  </div>
{% endblock %}