mscApplications/applicant/urls.py
from django.urls import  path
from .views import *

app_name = 'applicant'
urlpatterns = [
    path('home', ApplicantHomeView.as_view(), name='applicant_home'),
    path('profile', ApplicantProfileDetailView.as_view(), name='applicant_profile'),
    path('profile/edit', ApplicantProfileUpdateView.as_view(), name='applicant_profile_edit'),
    path('<int:pk>/detail', ApplicantDetailView.as_view(), name='applicant_detail'),
    path('applications', ApplicantApplicationListView.as_view(), name='applicant_applications'),
]

mscApplications/evaluator/urls.py
from django.urls import  path
from .views import *

app_name = 'evaluator'

urlpatterns = [
    path('home', EvaluatorHomeView.as_view(), name='evaluator_home'),
    path('profile', EvaluatorProfileDetailView.as_view(), name='evaluator_profile'),
    path('profile/edit', EvaluatorProfileUpdateView.as_view(), name='evaluator_profile_edit'),
    path('calls', EvaluatorCallListView.as_view(),name='evaluator_calls'),
    path('create', EvaluatorCreateView.as_view(),name='evaluator_create'),
    path('<int:pk>/delete', EvaluatorDeleteView.as_view(),name='evaluator_delete'),
    path('<int:pk>/update', EvaluatorUpdateView.as_view(),name='evaluator_update'),

]

mscApplications/msc/urls.py
from django.urls import  path
from .views import *

app_name = 'msc'

urlpatterns = [
    path('calls', CallListView.as_view(), name='call_list'),
    path('calls/create', CallCreateView.as_view(), name='call_create'),
    path('calls/<int:pk>/detail', CallDetailView.as_view(), name='call_detail'),
    path('calls/<int:pk>/delete', CallDeleteView.as_view(), name='call_delete'),
    path('calls/<int:pk>/update', CallUpdateView.as_view(), name='call_update'),
    path('calls/<int:pk>/applications', ApplicationListView.as_view(), name='call_application_list'),
    path('calls/<int:pk>/new-application', ApplicationCreateView.as_view(), name='call_new_application'),
    path('calls/<int:call_pk>/applications/<int:pk>/admit', ApplicationAdmitView.as_view(), name='call_application_admit'),
    path('programmes', MscProgrammeListView.as_view(), name='msc_programme_list'),
    path('programmes/create', MscProgrammeCreateView.as_view(), name='msc_programme_create'),
    path('programmes/<int:pk>', MscProgrammeDetailView.as_view(), name='msc_programme_detail'),
    path('programmes/<int:pk>/edit', MscProgrammeUpdateView.as_view(), name='msc_programme_update'),
    path('programmes/<int:pk>/delete', MscProgrammeDeleteView.as_view(), name='msc_programme_delete'),
]

mscApplications/mscApplications/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from .views import HomeView


urlpatterns = [
    path("accounts/", include("allauth.urls")),
    path("users/", include("user_account.urls", namespace="user_account")),
    path(
        "applicant/",
        include(
            "applicant.urls",
            namespace="applicant",
        ),
    ),
    path(
        "evaluator/",
        include("evaluator.urls",
        namespace="evaluator",
        ),
    ),
    path(
        "secretary/",
        include("secretary.urls",
        namespace="secretary",
        ),
    ),
    path(
        "msc/",
        include("msc.urls",
        namespace="msc",
        ),

    ),
    path(
        "org/",
        include("institution.urls",
        namespace="org",
        ),

    ),
    path("", HomeView.as_view(), name='home'),
    path("admin/", admin.site.urls),
    path("i18n/", include("django_translation_flags.urls")),
]
if settings.DEBUG==True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mscApplications/secretary/urls.py
from django.urls import  path
from .views import *

app_name = 'secretary'

urlpatterns = [
    path('home', SecretaryHome.as_view(), name='secretary_home'),
     path('profile', SecretaryProfileDetailView.as_view(), name='secretary_profile'),
    path('profile/edit', SecretaryProfileUpdateView.as_view(), name='secretary_profile_edit'),
    path('calls', SecretaryCallListView.as_view(), name='secretary_calls'),
    path('programmes', SecretaryMscProgrammeListView.as_view(), name='secretary_programmes'),
    path('evaluators', SecretaryEvaluatorListView.as_view(), name='secretary_evaluators'),
]

mscApplications/user_account/urls.py
from django.conf.urls import url
from django.urls import path, include
from .views import *
from django.contrib.auth import views as auth_views

app_name = "user_account"


urlpatterns = [
    path("check", CheckUser.as_view(), name="check-user"),
    path("change-password", ChangePasswordView.as_view(), name="user_change_password"),
]

mscApplications/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    {% load static %}
    {% load i18n %}
    {% load bootstrap5 %}
    {% block meta_tags %}
      <meta charset="UTF-8"/>
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    {% endblock meta_tags %}
    {% block stylesheets %}
      {% bootstrap_css %}
      <link rel="shortcut icon" type="image/png" href="{% static '/img/mortarboard.png' %}"/>
      <link rel="stylesheet" type="text/css" href="{% static '/css/app.css' %}" >
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    {% endblock %}
    {% block extra_css %}{% endblock extra_css %}
    {% block js %}
      {% bootstrap_javascript %}
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    {% endblock %}
      <title>{% block title %}{% endblock %}</title>
  </head>
  <body class="d-flex flex-column min-vh-100">
    {% block navbar %}
        {% include 'navbar.html' %}
    {% endblock %}
    </div>
    <div class="container flex-grow-1">
      {% if messages %}
        {% for message in messages %}
            <div class="toast show " role="alert" aria-live="assertive" aria-atomic="true"  style="position: absolute;top: 30; right: 20px; z-index:1;">
              <div class="toast-header">
                <strong class="me-auto">MSC Applications</strong>
                <small class="text-muted">Just Now</small>
                <button type="button" class="btn-close" data-bs-dismiss="toast"></button>
              </div>
              <div class="toast-body">
                {{ message }}
              </div>
            </div>
        {% endfor %}
      {% endif %}
      <br>
      <br>
      {% block content %}{% endblock %}
      <br>
      <br>
    </div>
    {% block footer %}
        {% include 'footer.html' %}
    {% endblock %}
    {% block javascript %}{% endblock javascript %}
  </body>
</html>

mscApplications/templates/footer.html
{% load i18n %}
{% load static %}
{% block footer %}
    <div class="footer msc-color">
    <div class="container">
        <div class="row">
            <div class="col col-12 col-md-4">
                <h3 class="text-white">Powered By</h3>
                <p class="text-white">Nisfeight8</p>
            </div>
            <div class="col col-12 col-md-4">
                <h3 class="text-white">{% translate "Open Calls" %}</h3>
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link text-white" href="{% url 'msc:call_list' %}">{% translate "List" %}</a>
                    </li>
                </ul>
            </div>
            <div class="col col-12 col-md-4">
                <h3 class="text-white">{% translate "MSC Programmes" %}</h3>
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link text-white" href="{% url 'msc:msc_programme_list' %}">{% translate "Search" %}</a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="row">
            <div class="col col-12 text-center">
                <p><img src="{% static 'img/sitelogo.png' %}" style="width:200px;"></p>
                <span class="text-muted">MSC Applications &copy; 2021</span>
            </div>
        </div>
    </div>
</div>

{% endblock %}

mscApplications/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block title %}{% translate "Welcome" %} {% endblock title %}

{% block content%}

    <figure class="text-center card card-body header-color text-white">
        <blockquote class="blockquote">
            <h5 style="display: inline">{% translate 'Welcome to' %} MSC Applications</h5>
        </blockquote>
    </figure>
    <div class="card">
        <div class="card-body ">
            <p>{% blocktranslate %} Welcome to MSC Applications ! Here you can find the MSC Programme wich fits you best. We provide you all the programmes from all the universities of Greece. {% endblocktranslate %} </p>
        </div>
    </div>
    <br>
    <figure class="text-center card card-body header-color text-white">
        <blockquote class="blockquote">
            <h5 style="display: inline">{% translate 'Our Services' %}</h5>
        </blockquote>
    </figure>
    <div class="row">
        <div class="col-12 col-md-6">
            <div class="card">
                <img src="{% static 'img/msc_programmes.jpg' %}" class="card-img-top" style="height: 18rem;">
                <div class="card-body">
                    <h5 class="card-title">{% translate "MSC Programmes" %}</h5>
                    <p class="card-text">{% blocktranslate %} Search and find every programme you want ! We provide you all the programmes in Greece ! {% endblocktranslate %}</p>
                    <a href="{% url 'msc:msc_programme_list' %}" class="btn msc-color text-white rounded-pill">{% translate "Open" %}</a>
                </div>
            </div>
        </div>
        <div class="col-12 col-sm-6">
            <div class="card">
                <img src="{% static 'img/open_calls.jpeg' %}" class="card-img-top" style="height: 18rem;">
                <div class="card-body">
                    <h5 class="card-title">{% translate "Open Calls" %}</h5>
                    <p class="card-text">{% blocktranslate %} View all the open calls to make a new application for the MSC Programme you prefer ! {% endblocktranslate %}</p>
                    <a href="{% url 'msc:call_list' %}" class="btn msc-color text-white rounded-pill">{% translate "Open" %}</a>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

mscApplications/templates/navbar.html
{% load static %}
{% load flags %}
{% load i18n %}

{% block navbar %}
    <div class="header navbar-expand-lg navbar-dark header-color text-white"	>
        <div class="container">
            <div class="navbar-nav flag"> {% languages %}</div>
        </div>
    </div>
    <nav class="navbar navbar-expand-lg d-flex navbar-dark msc-color text-white "	>
        <div class="container">
            {% if user.is_authenticated %}
                <button class="btn float-end" data-bs-toggle="offcanvas" data-bs-target="#offcanvas" role="button">
                    <i class="bi bi-list text-white fs-3" data-bs-toggle="offcanvas" data-bs-target="#offcanvas"></i>
                </button>
            {% endif %}
            <a href="{% url 'home' %}" class="navbar-brand" >
                <img src="{% static 'img/sitelogo.png' %}" width="300" height="60" alt="">
            </a>
            <div class="navbar-nav ms-auto">
                <a  href="{% url 'msc:msc_programme_list' %}"
                    class="nav-link"><i class="fs-5 bi bi-easel"></i> {% translate "MSC Programmes" %} 
                </a>
                <a  href="{% url 'msc:call_list' %}"
                    class="nav-link"><i class="fs-5 bi bi-calendar2-range"></i> {% translate "Open Calls" %} 
                </a>
                {% if not user.is_authenticated %}
                    <a href="{% url 'account_login' %}"
                            class="nav-link"><i class="fs-5 bi bi-box-arrow-in-right"></i> {% translate "Login" %}</a>
                {% endif %}
            </div>
        </div>
    </nav>
    {% if user.is_authenticated %}
        <div class="offcanvas offcanvas-start w-25" tabindex="-1" id="offcanvas" data-bs-keyboard="false" data-bs-backdrop="false">
            <div class="offcanvas-header">
                <h6 class="offcanvas-title d-none d-sm-block" id="offcanvas">Menu</h6>
                <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
            </div>
            <div class="offcanvas-body px-0">
                <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-start" id="menu">
                    {% if user.is_applicant %}
                        <li >
                            <a href="{% url 'applicant:applicant_home' %}" class="nav-link text-truncate">
                                <i class="fs-5 bi-house"></i><span class="ms-1 d-none d-sm-inline">Home</span>
                            </a>
                        </li>
                        <li >
                            <a href="{% url 'applicant:applicant_applications' %}" class="nav-link text-truncate">
                                <i class="fs-5 bi bi-card-checklist"></i><span class="ms-1 d-none d-sm-inline">{% translate "My Applications" %}</span>
                            </a>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="nav-link dropdown-toggle  text-truncate" id="dropdown" data-bs-toggle="dropdown" aria-expanded="false">
                                <i class="fs-5 bi bi-person-circle"></i><span class="ms-1 d-none d-sm-inline">{% translate "Profile" %}</span>
                            </a>
                            <ul class="dropdown-menu text-small shadow" aria-labelledby="dropdown">
                                <li><a class="dropdown-item" href="{% url 'applicant:applicant_profile' %}">{% translate "View profile" %}</a></li>
                                <li><a class="dropdown-item" href="{% url 'applicant:applicant_profile_edit' %}">{% translate "Edit Profile" %}</a></li>
                                <li><a class="dropdown-item" href="{% url 'user_account:user_change_password' %}">{% translate "Change Password" %}</a></li>
                            </ul>
                        </li>
                    {% endif %}
                    {% if user.is_evaluator %}
                        <li >
                            <a href="{% url 'evaluator:evaluator_home' %}" class="nav-link text-truncate">
                                <i class="fs-5 bi-house"></i><span class="ms-1 d-none d-sm-inline">{% translate "Home" %}</span>
                            </a>
                        </li>
                        <li >
                            <a href="{% url 'evaluator:evaluator_calls' %}" class="nav-link text-truncate">
                                <i class="fs-5 bi bi-calendar2-range"></i><span class="ms-1 d-none d-sm-inline">{% translate "My Calls" %}</span>
                            </a>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="nav-link dropdown-toggle  text-truncate" id="dropdown" data-bs-toggle="dropdown" aria-expanded="false">
                                <i class="fs-5 bi bi-person-circle"></i><span class="ms-1 d-none d-sm-inline">{% translate "Profile" %}</span>
                            </a>
                            <ul class="dropdown-menu text-small shadow" aria-labelledby="dropdown">
                                <li><a class="dropdown-item" href="{% url 'evaluator:evaluator_profile' %}">{% translate "View profile" %}</a></li>
                                <li><a class="dropdown-item" href="{% url 'evaluator:evaluator_profile_edit' %}">{% translate "Edit Profile" %}</a></li>
                                <li><a class="dropdown-item" href="{% url 'user_account:user_change_password' %}">{% translate "Change Password" %}</a></li>
                            </ul>
                        </li>
                    {% endif %}
                    {% if user.is_secretary %}
                        <li >
                            <a href="{% url 'secretary:secretary_home' %}" class="nav-link text-truncate">
                                <i class="fs-5 bi-house"></i><span class="ms-1 d-none d-sm-inline">{% translate "Home" %}</span>
                            </a>
                        </li>
                        <li >
                            <a href="{% url 'secretary:secretary_calls' %}" class="nav-link text-truncate">
                                <i class="fs-5 bi bi-calendar2-range"></i><span class="ms-1 d-none d-sm-inline">{% translate "Calls" %}</span>
                            </a>
                        </li>
                        <li >
                            <a href="{% url 'secretary:secretary_programmes' %}" class="nav-link text-truncate">
                                <i class="fs-5 bi bi-easel"></i><span class="ms-1 d-none d-sm-inline">{% translate "MSC Programmes" %}</span>
                            </a>
                        </li>
                        <li >
                            <a href="{% url 'secretary:secretary_evaluators' %}" class="nav-link text-truncate">
                                <i class="bi bi-people-fill"></i><span class="ms-1 d-none d-sm-inline">{% translate "Evaluators" %}</span>
                            </a>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="nav-link dropdown-toggle  text-truncate" id="dropdown" data-bs-toggle="dropdown" aria-expanded="false">
                                <i class="fs-5 bi bi-person-circle"></i><span class="ms-1 d-none d-sm-inline">{% translate "Profile" %}</span>
                            </a>
                            <ul class="dropdown-menu text-small shadow" aria-labelledby="dropdown">
                                <li><a class="dropdown-item" href="{% url 'secretary:secretary_profile' %}">{% translate "View profile" %}</a></li>
                                <li><a class="dropdown-item" href="{% url 'secretary:secretary_profile_edit' %}">{% translate "Edit Profile" %}</a></li>
                                <li><a class="dropdown-item" href="{% url 'user_account:user_change_password' %}">{% translate "Change Password" %}</a></li>
                            </ul>
                        </li>
                    {% endif %}
                    </hr>
                    <li>
                        <a href="{% url 'account_logout' %}" class="nav-link text-truncate">
                            <i class="fs-5 bi bi-box-arrow-left"></i><span class="ms-1 d-none d-sm-inline">{% translate "Logout" %}</span> </a>
                    </li>
                </ul>
            </div>
        </div>
    {% endif %}
{% endblock %}